from random import randint

LOREM_IPSUM = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque finibus, sapien in sodales porta, quam neque ultrices elit, eu fringilla velit tortor ac magna. Mauris scelerisque mauris auctor auctor ultricies. Aliquam et nisl augue. Aliquam turpis urna, aliquet in diam ac, blandit suscipit nulla. Phasellus placerat id leo ut molestie. Cras sed aliquam ligula. Aliquam blandit lobortis quam nec malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin eu mauris feugiat, pulvinar augue eu, convallis odio. Sed quis elementum neque. Sed metus enim, fermentum a odio id, euismod sagittis mauris. Duis ut porttitor odio, ac facilisis lacus.
Nam lacus nisl, dapibus quis turpis ac, rutrum ullamcorper felis. Curabitur consequat, elit sed gravida egestas, metus arcu consequat libero, sed tincidunt arcu orci efficitur tellus. Aenean malesuada, nisi ut semper finibus, enim nibh varius est, eget egestas erat elit quis tellus. Nullam magna nisi, rhoncus maximus lorem sit amet, lobortis rhoncus nulla. Etiam quis justo tincidunt, eleifend massa id, dignissim felis. Sed lorem dui, convallis ac venenatis sed, porta luctus justo. Nulla a mi quis tellus dapibus hendrerit. Mauris suscipit placerat urna tempor malesuada. Mauris ut mi vitae sem venenatis elementum. Nam dictum sapien lectus, et dapibus nisl tristique nec. Pellentesque pretium turpis lorem, semper pulvinar lectus cursus nec. Maecenas vehicula ut odio vitae dictum. Vestibulum id ullamcorper nisi. Sed a auctor orci, vel feugiat justo.
Proin dictum massa sed mi elementum pulvinar. Quisque imperdiet lacinia varius. Fusce cursus arcu at scelerisque imperdiet. Suspendisse vitae maximus ipsum. Aenean consequat sagittis massa, sit amet suscipit odio posuere ut. Morbi consequat tempor ante, eu feugiat mi. Aliquam eu massa vel turpis auctor egestas. Donec blandit porta ex. Pellentesque vel diam augue. Praesent sed lacus in lacus tempus tempor quis id sem. Praesent porta turpis id purus luctus elementum. Integer volutpat ornare sem nec maximus. Integer at quam vitae purus egestas tempor. Aliquam ut iaculis mauris, at elementum elit.
Praesent pulvinar luctus odio. Donec et elit ut elit tincidunt dapibus. Vivamus tincidunt, elit eu posuere luctus, lectus ligula gravida velit, finibus fermentum odio mi ac massa. Cras sit amet quam ex. Sed suscipit nisi in maximus maximus. Fusce finibus pretium vehicula. Donec fermentum turpis accumsan sapien cursus, et aliquam urna tincidunt. Maecenas sagittis magna vitae orci condimentum rhoncus.
Suspendisse semper libero a arcu vehicula semper. Aliquam vel vestibulum velit, sit amet convallis magna. Ut a magna dignissim, semper orci convallis, vulputate risus. Integer a augue gravida diam tempus pulvinar. Nunc nibh quam, mattis ut pulvinar vel, facilisis id quam. Ut faucibus blandit magna eu maximus. Suspendisse vel facilisis ligula. Fusce convallis cursus dui, ac dapibus massa porttitor eget. Phasellus vel sollicitudin erat. In hendrerit dignissim volutpat.
Donec fringilla, ante nec venenatis auctor, quam nisl pellentesque sem, in porta tellus eros ut sem. Quisque facilisis tincidunt augue. Mauris fringilla mi vel ipsum vulputate congue. Phasellus lobortis nec mauris vel congue. Vivamus sit amet pellentesque nibh. Duis lectus nunc, consectetur et accumsan at, sodales at lectus. Mauris sit amet dictum augue. Praesent turpis lectus, imperdiet at dictum a, posuere a sapien.'''

def paragraph():
    paragraphs = LOREM_IPSUM.split("\n")
    rows = len(paragraphs)
    index = randint(0,rows-1)
    return paragraphs[index]